# Generated by Django 5.1 on 2024-08-15 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nascimento', models.DateTimeField(blank=True, null=True, verbose_name='data de nascimento do autor')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='nome do usuario')),
                ('email', models.CharField(blank=True, max_length=100)),
                ('nascimento', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(blank=True, null=True, verbose_name='usuario é funcionario?')),
                ('pendente', models.BooleanField(null=True)),
                ('emprestimo', models.DateTimeField(blank=True, null=True)),
                ('devolução', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='titulos')),
                ('categoria', models.CharField(max_length=100, verbose_name='categorias')),
                ('editora', models.CharField(max_length=100, verbose_name='editoras')),
                ('ano', models.DateTimeField(null=True, verbose_name='ano do livro')),
                ('disponibilidade', models.BooleanField(null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.autor', verbose_name='autor do livro')),
            ],
        ),
        migrations.CreateModel(
            name='emprestimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.livros')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.usuario')),
            ],
        ),
    ]
